# Generated by Django 3.0.3 on 2020-08-06 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueuuid', models.CharField(default=uuid.UUID('2a296948-d7a0-11ea-9eca-0002c951f640'), max_length=64, verbose_name='Ticket UUID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('status', models.IntegerField(choices=[(0, 'Closed'), (1, 'Open')], verbose_name='Status')),
                ('resolution', models.IntegerField(choices=[(0, "Won't-Fix"), (1, 'Fixed'), (2, 'Rejected'), (3, 'External Bug'), (4, 'Not A Bug'), (5, 'Duplicate')], verbose_name='Resolution')),
                ('issuetype', models.IntegerField(choices=[(0, 'Bug'), (1, 'Feature')], verbose_name='Type')),
                ('severity', models.IntegerField(choices=[(0, 'Minor'), (1, 'Medium'), (2, 'High'), (3, 'URGENT')], verbose_name='Severity')),
                ('rooted', models.BooleanField(verbose_name='Device is Rooted')),
                ('device', models.CharField(max_length=64, verbose_name='Device')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('name', models.CharField(max_length=64, verbose_name='Username')),
                ('text', models.TextField(verbose_name='Comment')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.Issue')),
            ],
        ),
    ]
