# Generated by Django 3.0.3 on 2020-08-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('issueuuid',
                 models.CharField(blank=True,
                                  default='d7caea31f9ea438799fea20901fbf8a0',
                                  max_length=64,
                                  verbose_name='Ticket UUID')),
                ('date',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='Creation Date')),
                ('updated',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='Update Date')),
                ('title', models.CharField(max_length=256,
                                           verbose_name='Title')),
                ('status',
                 models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')],
                                     default=1,
                                     verbose_name='Status')),
                ('resolution',
                 models.IntegerField(blank=True,
                                     choices=[(0, "Won't-Fix"), (1, 'Fixed'),
                                              (2, 'Rejected'),
                                              (3, 'External Bug'),
                                              (4, 'Not A Bug'),
                                              (5, 'Duplicate'),
                                              (6, 'Confirmed')],
                                     null=True,
                                     verbose_name='Resolution')),
                ('issuetype',
                 models.IntegerField(choices=[(0, 'Bug'), (1, 'Feature')],
                                     default=0,
                                     verbose_name='Type')),
                ('severity',
                 models.IntegerField(choices=[(0, 'Minor'), (1, 'Medium'),
                                              (2, 'High'), (3, 'URGENT')],
                                     default=0,
                                     verbose_name='Severity')),
                ('rooted',
                 models.BooleanField(default=False,
                                     verbose_name='Device is Rooted')),
                ('device',
                 models.CharField(max_length=64, verbose_name='Device')),
                ('username',
                 models.CharField(max_length=64, verbose_name='Username')),
                ('locked',
                 models.BooleanField(default=False, verbose_name='Locked')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('date',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='Creation Date')),
                ('name',
                 models.CharField(max_length=64, verbose_name='Username')),
                ('text', models.TextField(verbose_name='Comment')),
                ('issue',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='bugs.Issue')),
            ],
        ),
    ]
