# Generated by Django 3.0.3 on 2020-08-06 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issuetype',
            field=models.IntegerField(choices=[(0, 'Bug'), (1, 'Feature')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueuuid',
            field=models.CharField(default=uuid.UUID('e70645d8-d7a8-11ea-a8a1-0002c951f640'), max_length=64, verbose_name='Ticket UUID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution',
            field=models.IntegerField(choices=[(0, "Won't-Fix"), (1, 'Fixed'), (2, 'Rejected'), (3, 'External Bug'), (4, 'Not A Bug'), (5, 'Duplicate')], null=True, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='rooted',
            field=models.BooleanField(default=False, verbose_name='Device is Rooted'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.IntegerField(choices=[(0, 'Minor'), (1, 'Medium'), (2, 'High'), (3, 'URGENT')], default=0, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Closed'), (1, 'Open')], default=1, verbose_name='Status'),
        ),
    ]
