# Generated by Django 3.0.3 on 2020-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueuuid',
            field=models.CharField(blank=True, default='f5a59a10a4e44ec2ae9c2f0ffe6d343f', max_length=64, verbose_name='Ticket UUID'),
        ),
    ]
