# Generated by Django 3.0.3 on 2020-08-06 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20200806_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueuuid',
            field=models.CharField(default=uuid.UUID('e9c46ef6-d7aa-11ea-8a0b-0002c951f640'), max_length=64, verbose_name='Ticket UUID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution',
            field=models.IntegerField(blank=True, choices=[(0, "Won't-Fix"), (1, 'Fixed'), (2, 'Rejected'), (3, 'External Bug'), (4, 'Not A Bug'), (5, 'Duplicate')], null=True, verbose_name='Resolution'),
        ),
    ]
