# Generated by Django 3.0.3 on 2020-08-06 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20200806_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueuuid',
            field=models.CharField(blank=True, default=uuid.UUID('27542892-d7ab-11ea-be44-0002c951f640'), max_length=64, verbose_name='Ticket UUID'),
        ),
    ]
