# Generated by Django 3.0.3 on 2020-08-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20200806_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueuuid',
            field=models.CharField(blank=True, default='afc73e0ad7ae11ea94ae0002c951f640', max_length=64, verbose_name='Ticket UUID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution',
            field=models.IntegerField(blank=True, choices=[(0, "Won't-Fix"), (1, 'Fixed'), (2, 'Rejected'), (3, 'External Bug'), (4, 'Not A Bug'), (5, 'Duplicate'), (6, 'Confirmed')], null=True, verbose_name='Resolution'),
        ),
    ]
