# Generated by Django 3.0.3 on 2020-08-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20200806_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueuuid',
            field=models.CharField(blank=True, default='2cd80976d89d11eabc0a0002c951f640', max_length=64, verbose_name='Ticket UUID'),
        ),
    ]
