# Generated by Django 3.0.3 on 2020-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_auto_20200807_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueuuid',
            field=models.CharField(blank=True, default='c38b83a4d8a511ea8a440002c951f640', max_length=64, verbose_name='Ticket UUID'),
        ),
    ]
